---
DICT:
  tono: ["殿", "殿、利息でござる！"]
  grimgar: ["グリムガル", "生きるって、簡単じゃない。", "灰と幻想のグリムガル", "ハルヒロ", "ランタ", "マナト", "モグゾー", "ユメ", "シホル", "メリイ", "レンジ", "キッカワ", "ブリトニー", "バルバラ", "アダチ", "ロン", "サッサ", "チビ", "ホーネン", "シノハラ", "ハヤシ", "ミチキ", "オグ", "ムツミ", "ささやき、詠唱、祈り、目覚めよ", "見習い義勇兵の長い一日"]
